from os import environ

AZURE_API_ENDPOINT = environ["AZURE_API_ENDPOINT"]
AZURE_API_KEY = environ["AZURE_API_KEY"]
AZURE_API_VERSION = environ["AZURE_API_VERSION"]
AZURE_DEPLOYMENT = environ["AZURE_DEPLOYMENT"]
